config/routes.rb
Rails.application.routes.draw do
  resources :cycles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cycles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/component.rb
class Component
  # Includes
  include ActiveModel::Model

  # Accessors
  attr_accessor :id, :name, :impacts

  # Assocication
end

app/models/cycle.rb
class Cycle < ApplicationRecord
  # Constants
  # Includes
  # Asssociation
  # Scopes
  # Attributes

  attribute :components

  # Accessors
  # Validations
  validates :name, presence: true
  # Class methods / Singleton Methods
  # Instance methods
  def total_impact
    component_total(components)
  end

  private

  # Get the total impacts value of a components with recursion
  def component_total(components, total = 0)
    components.each do |comp|
      total += impact_total(comp) if comp['impacts'].present?
      total += component_total(comp['components']) if comp['components'].present?
    end
    total
  end

  def impact_total(comp)
    comp['impacts'].values.map(&:to_i).sum
  end
end

app/models/impact.rb
class Impact
  include ActiveModel::Model

  attr_accessor :id, :climate_change, :water_use
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cycles_controller.rb
class CyclesController < ApplicationController
  before_action :set_cycle, only: %i[show edit update destroy]

  # GET /cycles or /cycles.json
  def index
    @cycles = Cycle.all
  end

  # GET /cycles/1 or /cycles/1.json
  def show; end

  # GET /cycles/new
  def new
    @cycle = Cycle.new
  end

  # GET /cycles/1/edit
  def edit; end

  # POST /cycles or /cycles.json
  def create
    @cycle = Cycle.new(cycle_params)

    respond_to do |format|
      if @cycle.save
        format.html { redirect_to cycles_path, notice: 'Cycle was successfully created.' }
        format.json { render :show, status: :created, location: @cycle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cycles/1 or /cycles/1.json
  def update
    respond_to do |format|
      if @cycle.update(cycle_params)
        format.html { redirect_to @cycle, notice: 'Cycle was successfully updated.' }
        format.json { render :show, status: :ok, location: @cycle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cycles/1 or /cycles/1.json
  def destroy
    @cycle.destroy
    respond_to do |format|
      format.html { redirect_to cycles_url, notice: 'Cycle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cycle
    @cycle = Cycle.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cycle_params
    # params.require(:cycle).permit(:name, components: [:name, { impacts: %i[climate_change water_use] }])
    params.require(:cycle).permit(:name,
                                  components: [:name,
                                               { impacts: %i[climate_change water_use],
                                                 components: [:name, { impacts: %i[climate_change water_use] }] }])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cycles_helper.rb
module CyclesHelper
end

app/views/cycles/_components.html.erb
<div class="component-fields">
  <div class="flex">
  <%= form.label :name, "Component name" %>
  <button data-action="click->cycle#removeComponent" class="text-sm text-red-600 ml-1">remove</button>
  </div>
  <%= form.text_field :name, class: 'block rounded-md w-1/2' %>

  <div data-cycle-target="impacts" class="impacts ml-3">
    <template data-cycle-target="impactsTemplate">
      <%= render "impacts" %>
    </template>
    <span data-action="click->cycle#addImpact" class="text-indigo-500 cursor-pointer mt-3 text-xs">Add impact</span>
  </div>

  <div class="subComponent ml-3">
    <template  data-cycle-target="subComponentTemplate">
      <%= form.fields_for "components[]", Component.new do |component| %>
        <%= render "sub_components",  form: component %>
      <% end %>
    </template>
    <span data-action="click->cycle#addSubComponent" class="text-indigo-500 cursor-pointer mt-3 text-xs">Add sub component</span>
  </div>

</div>

app/views/cycles/_form.html.erb
<%= form_with(model: cycle, local: true) do |form| %>
  <% if cycle.errors.any? %>
    <div role="alert">
      <div class="bg-red-500 text-white font-bold rounded-t px-4 py-2">
        <span><%= pluralize(cycle.errors.count, "error") %> prohibited this cycle from being saved:</span>
      </div>
      <div class="border border-t-0 border-red-400 rounded-b bg-red-100 px-4 py-3 text-red-700">
        <ul>
        <% cycle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

    <div class="block mt-4">
    <%= form.label :name , class:'text-gray-700'  %>
    <%= form.text_field :name, class: 'block rounded-md w-1/2' %>
  </div>

    <div class="block mt-4 ml-4" data-controller="cycle">
      <div data-cycle-target="components">
      <template data-cycle-target="componentsTemplate">
        <%= form.fields_for "components[]", Component.new do |component| %>
          <%= render "components",  form: component %>
        <% end %>
      </template>
      <span data-action="click->cycle#addComponent" class="text-indigo-500 cursor-pointer mt-3">Add component</span>
      <div>
    </div>


  <div class="block mt-4">
    <% if cycle.persisted? %>
      <div class="">
        <%= link_to 'Destroy', cycle, method: :delete, class: "text-red-700", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'py-2 px-3 bg-gray-700 text-white rounded-lg' %>

    <% if cycle.persisted? %>
      <%= link_to "Cancel", cycle, class: "py-2 px-3 bg-gray-700 text-white rounded-lg" %>
    <% else %>
      <%= link_to "Cancel", cycles_path, class: "py-2 px-3 bg-gray-700 text-white rounded-lg" %>
    <% end %>
  </div>
<% end %>

app/views/cycles/_impacts.html.erb
<div class="impacts-fields">
  <div class="">
    <%= label_tag 'cycle[components][][impacts][climate_change]', "Climate Change" %>
    <%= text_field_tag 'cycle[components][][impacts][climate_change]' %>

  </div>
  <div class="">
    <%= label_tag 'cycle[components][][impacts][water_use]', "Water Use" %>
    <%= text_field_tag 'cycle[components][][impacts][water_use]' %>
  </div>
</div>

app/views/cycles/_sub_components.html.erb
<div class="component-fields">
  <%= label_tag "cycle[components][][components][][name]", "Subcomponent name" %>
  <%= text_field_tag "cycle[components][][components][][name]",{}, class: 'w-1/2' %>

  <div data-cycle-target="impacts" class="impacts ml-3">
    <template data-cycle-target="impactsTemplate">
      <%= render "sub_impacts" %>
    </template>
    <span data-action="click->cycle#addImpact" class="text-indigo-500 cursor-pointer mt-3">Add impact</span>
  </div>

</div>

app/views/cycles/_sub_impacts.html.erb
<div class="impacts-fields">
  <div class="">
    <%= label_tag 'cycle[components][][components][][impacts][climate_change]', "Climate Change" %>
    <%= text_field_tag 'cycle[components][][components][][impacts][climate_change]' %>
  </div>
  <div class="">
    <%= label_tag 'cycle[components][][components][][impacts][water_use]', "Water Use" %>
    <%= text_field_tag 'cycle[components][][components][][impacts][water_use]' %>
  </div>
</div>

app/views/cycles/edit.html.erb
<div class="py-4 align-middle inline-block min-w-full md:px-6 lg: px-8">
  <div class="shadow-md sm:rounded-lg bg-gray-100">
    <h1 class="font-bold text-gray-800 text-lg leading-tight px-3 py-4">New cycle</h1>

    <div class="sm:p-6 lg:p-8 bg-white">
     <%= render 'form', cycle: @cycle %>
    </div>

  </div>
</div>

app/views/cycles/index.html.erb
<div class="flex justify-between sm:px-6 lg:px-8 py-6">
  <div class="">
    <h1 class="text-gray-700 font-bold text-xl">Cycles</h1>
  </div>

  <div class="">
  <%= link_to new_cycle_path, class: 'py-2 px-3 bg-gray-700 text-white rounded-lg' do %>
    Add New Cycle
  <% end %>
  </div>
</div>

<div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
  <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>

            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Total Impact</th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Components</th>


        </tr>
      </thead>

      <tbody class="bg-white divide-y divide-gray-200">
        <% @cycles.each do |cycle| %>
          <%= content_tag :tr, id: dom_id(cycle), class: dom_class(cycle) do %>
              <td class="text-indigo-600 hover:text-indigo-900 px-6 py-4"><%= link_to cycle.name, cycle %></td>
              <td class="text-indigo-600 hover:text-indigo-900 px-6 py-4"><%= cycle.total_impact %></td>
              <td class="text-indigo-600 hover:text-indigo-900 px-6 py-4"><%= link_to "View Raw Json", cycle_path(cycle, format: :json) %></td>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/cycles/new.html.erb
<div class="py-4 align-middle inline-block min-w-full md:px-6 lg: px-8">
  <div class="shadow-md sm:rounded-lg bg-gray-100">
    <h1 class="font-bold text-gray-800 text-lg leading-tight px-3 py-4">New cycle</h1>

    <div class="sm:p-6 lg:p-8 bg-white">
     <%= render 'form', cycle: @cycle %>
    </div>

  </div>
</div>

app/views/cycles/show.html.erb
<div class="bg-white shadow overflow-hidden sm:rounded-lg sm:m-6 lg:m-12">
  <div class="px-4 py-5 sm:px-6">
   <div class="flex justify-between">
    <div>
    <h3 class="text-lg leading-6 font-medium text-gray-900">
      Cycles Information
    </h3>
    <p class="mt-1 max-w-2xl text-sm text-gray-500">
      Cycles details.
    </p>
    </div>
    <div>
    <%= link_to cycles_path, class: 'px-3 py-2 bg-gray-700 rounded-md text-white' do %>
      All Cycles
    <% end %>
    </div>

   </div>

  </div>
  <div class="border-t border-gray-200">
  <dl>
    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
      <dt class="text-sm font-medium text-gray-500">
        Name
      </dt>
      <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
        <%= @cycle.name %>
      </dd>
      <dt class="text-sm font-medium text-gray-500">
        Components
      </dt>
      <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
        <%= @cycle.components %>
      </dd>
    </div
  </dl>

  <div class="m-3">
  <%= link_to edit_cycle_path(@cycle), class: 'px-3 py-2 bg-gray-700 rounded-md text-white' do %>
    Edit
  <% end %>
  </div>
  
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Earthester</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>